# Generated by Django 3.1.6 on 2021-02-16 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dacha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 16, 17, 39, 29, 871564, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dacha.material')),
            ],
        ),
    ]
