# Generated by Django 3.1.6 on 2021-02-18 19:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dacha', '0003_auto_20210218_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 19, 17, 33, 114885, tzinfo=utc)),
        ),
    ]
