# Generated by Django 3.1.6 on 2021-02-19 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dacha', '0004_auto_20210218_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 11, 51, 5, 573411, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('notes', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('materials', models.ManyToManyField(related_name='lessons', to='dacha.Material')),
            ],
        ),
    ]
